In [10]:
import numpy as np
import pandas as pd
import re


In [82]:
def getEachRowAsSingleString(filename):
    data01 = open(filename, "r")
    lines = data01.read().splitlines()
    return lines

def getEachRowAsSplitList(filename, delim):
    data01 = open(filename, "r")
    lines = data01.read().splitlines()
    ll = []
    for l in lines :
        ll.append(l.split(delim))
    return ll

def most_frequent(List):
    return max(set(List), key = List.count)

def least_frequent(List):
    return min(set(List), key = List.count)

def mergedLists(lists) :
    out = []
    while len(lists)>0:
        first, *rest = lists
        first = set(first)
        lf = -1
        while len(first)>lf:
            lf = len(first)
            rest2 = []
            for r in rest:
                if len(first.intersection(set(r)))>0:
                    first |= set(r)
                else:
                    rest2.append(r)     
            rest = rest2

        out.append(first)
        lists = rest
    return out
        
def demoInput() :
    lines = getEachRowAsSplitList("demoinput.txt", " ")
    multilines = getEachRowAsSingleString("demoinput.txt")
    print("getEachRowAsSplitList", lines)
    print("getEachRowAsSingleString", multilines)

def get8Coordineighbours(x,y) :
    neigh = []
    neigh.append((x-1,y-1))
    neigh.append((x-1,y))
    neigh.append((x-1,y+1))
    neigh.append((x,y-1))
    neigh.append((x,y+1))
    neigh.append((x+1,y-1))
    neigh.append((x+1,y))
    neigh.append((x+1,y+1))
    return neigh

def get4Coordineighbours(x,y) :
    neigh = []
    neigh.append((x-1,y))
    neigh.append((x,y-1))
    neigh.append((x,y+1))
    neigh.append((x+1,y))
    return neigh



demoInput()

getEachRowAsSplitList [['hej', 'hej'], ['hej', 'nej']]
getEachRowAsSingleString ['hej hej', 'hej nej']


In [5]:
def task01() : 
    print("TASK01")
    lines = getEachRowAsSingleString("01.txt")
    val = 100000000
    increased = 0
    tripInc = 0
    cnt = 0
    for l in lines :
        #B-TASK
        if cnt > 3 :
            firstTrip = int(lines[cnt-4]) + int(lines[cnt-3]) + int(lines[cnt-2])
            secTrip = int(lines[cnt-3]) + int(lines[cnt-2]) + int(lines[cnt-1])
            thirdTrip = int(lines[cnt-2]) + int(lines[cnt-1]) + int(lines[cnt])
            if secTrip > firstTrip :
                tripInc = tripInc + 1
            if cnt == len(lines) - 1 :
                if thirdTrip > secTrip :
                    tripInc = tripInc + 1
        #A-TASK
        if val <=int(l) :
            increased = increased + 1
        val = int(l) 
        cnt = cnt + 1 
    print("1A", increased) 
    print("1B" ,tripInc)

task01()


TASK01
1A 1342
1B 1378


In [6]:
def task02() :
    print("TasK02")
    lines = getEachRowAsSplitList("02.txt", " ")
    f = 0
    d1 = 0 
    d2 = 0 
    a = 0
    hor = 0
    for l in lines :
        if l[0] == "down":
            d1 = d1 + int(l[1])
            a = a + int(l[1])
        elif l[0] == "up":
            d1 = d1 - int(l[1])
            a = a - int(l[1])
        elif l[0] == "forward" :
            f = f + int(l[1])
            hor = hor + int(l[1])
            d2 = d2 + (a*int(l[1]))
        
    print("2A", d1*f)
    print("2B", d2*hor)

task02()

TasK02
2A 1690020
2B 1408487760


In [7]:
def task03() :
    print("TasK03")
    lines = getEachRowAsSingleString("03.txt")
    nums = getFrequency(lines)
    gamma = ""
    epsilon = ""
    for a in nums :
        if (nums[a]) > 500 :
            gamma = gamma + "1"
            epsilon = epsilon + "0"
        else :
            gamma = gamma + "0"
            epsilon = epsilon + "1"
    
    print("03A", int(epsilon,2) * int(gamma,2))

    # oxygen generator rating
    oxygens = lines
    seed = ""
    for a in range(12) :
        if nums[str(a)] >= (len(oxygens) / 2):
            seed = seed + "1"
            oxygens = getFilteredList(oxygens, seed)
        else :
            seed = seed + "0"
            oxygens = getFilteredList(oxygens, seed)
            
        nums = getFrequency(oxygens)
        if len(oxygens) == 1 :
            break


    #FRESH VARIABLES for CO2 scrubber rating
    seed = ""
    nums = getFrequency(lines)
    scrubber = lines   
   
    for a in range(12) :
        if nums[str(a)] >= len(scrubber) / 2:
            seed = seed + "0"
            scrubber = getFilteredList(scrubber, seed)
        else :
            seed = seed + "1"
            scrubber = getFilteredList(scrubber, seed)
            
        nums = getFrequency(scrubber)
        if len(scrubber) == 1 :
            break

    print("03b", int(oxygens[0],2) * int(scrubber[0],2))


def getFrequency(lines) :
    nums = getCleanDict()
    for li in lines :
        index = 0
        for l in li :
            nums[str(index)] =  nums[str(index)] + int(l)
            index = index + 1
    return nums

def getFilteredList(liii, seed) :
    newList = []
    for l  in liii  :
        if str(l).startswith(seed) :
            newList.append(l)
    return newList

def getCleanDict() :
    return {'0' : 0, '1' : 0, '2' : 0, '3' : 0,
            '4' : 0, '5' : 0, '6' : 0, '7' : 0, 
            '8' : 0, '9' : 0, '10' : 0, '11' : 0}

task03()

TasK03
03A 852500
03b 1007985


In [8]:
def task04() : 
    #Where did it go I sup it away??
    print('NYI')
    print("TasK04")


In [9]:
def task05() :
    print("TasK05")

    lines = getEachRowAsSplitList("05.txt", ",")
    dim = 1000
    board = np.zeros((dim,dim))
    for l in lines :
        x1 = int(l[0])
        y1 = int(l[1])
        x2 = int(l[2])
        y2 = int(l[3])
        
        if x1 == x2 :
            i = y2
            if y2 >= y1 :
                while i >= y1 :
                    board[x1][i] = board[x1][i] + 1
                    i = i - 1
            else :
                while i <=  y1 :
                    board[x1][i] = board[x1][i] + 1
                    i = i + 1
        elif y1 == y2 :
            i = x2
            if x2 >= x1 :
                while i  >= x1 :
                    board[i][y1] = board[i][y1] + 1
                    i = i - 1
            else :
                while i <= x1 :
                    board[i][y1] = board[i][y1] + 1
                    i = i + 1

        ## PART OF B - DIAGONALS CHECKER.
        else :
            i = x2
            j = y2                
            if x1 > x2 : 
                if y1 > y2 :
                    while i <= x1 :
                        board[i][j] = board[i][j] + 1
                        i = i + 1
                        j = j + 1
                else :
                    while i <= x1 :
                        board[i][j] = board[i][j] + 1
                        i = i + 1
                        j = j - 1
            elif y1 > y2 : 
                while j <= y1 :
                    board[i][j] = board[i][j] + 1
                    i = i - 1
                    j = j + 1
            else :
                while j >= y1 :
                    board[i][j] = board[i][j] + 1
                    i = i - 1
                    j = j - 1
    counter = 0
    for i in range(dim) :
        for j in range(dim) :
            if board[i][j] > 1 :
                counter = counter +1 

    print(board)                
    print("05b", counter)
task05()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
05b 22213


In [10]:
def task06() :
    fish = [5,4,3,5,1,1,2,1,2,1,3,2,3,4,5,1,2,4,3,2,5,1,4,2,1,1,2,5,4,4,4,1,5,4,5,2,1,2,5,5,4,1,3,1,4,2,4,2,5,1,3,5,3,2,3,1,1,4,5,2,4,3,1,5,5,1,3,1,3,2,2,4,1,3,4,3,3,4,1,3,4,3,4,5,2,1,1,1,4,5,5,1,1,3,2,4,1,2,2,2,4,1,2,5,5,1,4,5,2,4,2,1,5,4,1,3,4,1,2,3,1,5,1,3,4,5,4,1,4,3,3,3,5,5,1,1,5,1,5,5,1,5,2,1,5,1,2,3,5,5,1,3,3,1,5,3,4,3,4,3,2,5,2,1,2,5,1,1,1,1,5,1,1,4,3,3,5,1,1,1,4,4,1,3,3,5,5,4,3,2,1,2,2,3,4,1,5,4,3,1,1,5,1,4,2,3,2,2,3,4,1,3,4,1,4,3,4,3,1,3,3,1,1,4,1,1,1,4,5,3,1,1,2,5,2,5,1,5,3,3,1,3,5,5,1,5,4,3,1,5,1,1,5,5,1,1,2,5,5,5,1,1,3,2,2,3,4,5,5,2,5,4,2,1,5,1,4,4,5,4,4,1,2,1,1,2,3,5,5,1,3,1,4,2,3,3,1,4,1,1]
    #fish = [3,4,3,1,2]
    print("TasK06")

    for day in range(80) :
        newSpawn = []
        counter = 0

        for a in fish :
            if( a == 0 ) :
                fish[counter] = 6
                newSpawn.append(8)
            else :
                fish[counter] = fish[counter] - 1 
            counter = counter + 1
        fish.extend(newSpawn)
    print("06a",day+1,len(fish))
    
    tot = 0
    for a in fish :
            if( a == 1 ) :
                tot = tot + 6206821033
            elif (a == 2) :
                tot = tot + 5617089148
            elif (a == 3) :
                tot = tot + 5217223242
            elif (a == 4) :
                tot = tot + 4726100874
            elif (a == 5) :
                tot = tot + 4368232009
    print("06b", tot )
task06()

06a 80 350917
06b 1098892254449521


In [15]:
def task07() :
    lines = getEachRowAsSplitList("07.txt", ",")
    print("TasK07")

    horz = []
    for ll in lines :
        for l in ll :
            horz.append(int(l))

    start = min(horz)
    stop = max(horz)
    minMove = 10000000000000
    best = 0

    while start < stop :
        sum = 0
        for h in horz :
            smaller = True
            for step in range(abs(h-start)) :
                sum = sum + step + 1
            if sum > minMove :
                smaller = False
                break
        if smaller :
            minMove = sum
            best = start
        
        start = start + 1
    print(best,minMove)
  
task07()

TasK07
5 168


In [56]:
def task08() :
    print("TasK08")
    lines = getEachRowAsSplitList("08.txt", " ")
    sum = 0
    counter = 0 
    for ll in lines :
        myVals = False 
        val = []
        oneChars = []
        occurances = ""
        #Segment B, F and E are lite a unique amount of times for 0+9 so just
        #count the occurance if one letter is the same as those assign that letter 
        #to the segment
        segmentB = ""
        segmentF = ""
        segmentE = ""

        for l in ll :
            if not myVals :
                occurances = occurances + l
                if len(l) == 2 :
                    oneChars = l
                if l == "|" :
                    myVals = True
                    a = occurances.count("a")
                    b = occurances.count("b")
                    c = occurances.count("c")
                    d = occurances.count("d")
                    e = occurances.count("e")
                    f = occurances.count("f")
                    g = occurances.count("g")
                    if a == 4 :
                        segmentE = "a"
                    elif a == 6 :
                        segmentB = "a"
                    elif a == 9 :
                        segmentF = "a"
                    
                    if b == 4 :
                        segmentE = "b"
                    elif b == 6 :
                        segmentB = "b"
                    elif b == 9 :
                        segmentF = "b"
                    
                    if c == 4 :
                        segmentE = "c"
                    elif c == 6 :
                        segmentB = "c"
                    elif c == 9 :
                        segmentF = "c"
                    
                    if d == 4 :
                        segmentE = "d"
                    elif d == 6 :
                        segmentB = "d"
                    elif d == 9 :
                        segmentF = "d"
                    
                    if e == 4 :
                        segmentE = "e"
                    elif e == 6 :
                        segmentB = "e"
                    elif e == 9 :
                        segmentF = "e"
                    
                    if f == 4 :
                        segmentE = "f"
                    elif f == 6 :
                        segmentB = "f"
                    elif f == 9 :
                        segmentF = "f"
                    
                    if g == 4 :
                        segmentE = "g"
                    elif g == 6 :
                        segmentB = "g"
                    elif g == 9 :
                        segmentF = "g"
            elif myVals:
            
                if len(l) == 2 :
                    counter = counter + 1
                    val.append(1)
                elif len(l) == 3 :
                    counter = counter + 1
                    val.append(7)
                elif len(l) == 4 :
                    counter = counter + 1
                    val.append(4)
                elif len(l) == 7 :
                    counter = counter + 1
                    val.append(8)
                elif len(l) == 5 :
                    #2,3,5
                    if l.count(segmentF) == 0 :
                        val.append(2)
                    elif l.count(segmentB) == 0 :
                        val.append(3)
                    else :
                        val.append(5)
                elif len(l) == 6 :
                    #6,9,0
                    if l.count(segmentE) == 0 :
                        val.append(9)
                    elif l.count(oneChars[0]) == 1 and l.count(oneChars[1]) == 1 :
                        val.append(0)
                    else :
                        val.append(6)  
                    
                  
            
        sum = sum +val[0]*1000 + val[1]*100 + val[2]*10 + val[3]*1 
    print("08a", counter)
    print("08b", sum)
task08()

TasK08
08a 264
08b 1063760


In [101]:
def task09() :
    print("TasK09")
    counterX = 0 
    lines = getEachRowAsSingleString("09.txt") 
    dimX = 100    
    dimY = 100
    map = np.zeros((dimX,dimY))
    basins = []

    for ll in lines :
        counterY = 0
        for l in ll :
            map[counterX,counterY] = int(l) + 1 
            counterY = counterY + 1 
            if int(l) != 9 :
                basins = inBasin(counterX,counterY, basins)
        counterX = counterX + 1 
        
    #09A
    valleySum = 0
    for x in range(dimX) :
        for y in range(dimY) :
            neigh = get4Coordineighbours(x,y)
            valley = True
            while len(neigh) != 0 :
                i,j = neigh.pop()
                if i > -1 and i < dimX and j > -1 and j < dimY :
                    if map[x,y] >= map[i,j] :
                        valley = False
                        break
            if valley :
                valleySum = valleySum + map[x,y]

    print('09A', valleySum)
    
    #09B
    basse = mergedLists(basins)
    lengths = []
    for b in basse :
        lengths.append(len(b))
    
    print("09B",sorted(lengths, reverse=True)[0]*sorted(lengths, reverse=True)[1]*sorted(lengths, reverse=True)[2])
    
def inBasin(x,y, basse):
    newBasin = [(x,y)]
    inBasse = False
    for b in basse :
        if (x-1,y) in b :
            b.extend(newBasin)         
            inBasse = True
        elif (x,y-1) in b :
            b.extend(newBasin)
            inBasse = True
        elif (x,y+1) in b :
            b.extend(newBasin)
            inBasse = True
        elif (x+1,y) in b :
            b.extend(newBasin)
            inBasse = True
    if not inBasse :
        basse.append(newBasin)
    return basse

task09()

TasK09
09A 436.0
09B 1317792


In [41]:
def task10() :

    print("TasK10")
    lines = getEachRowAsSingleString("10.txt") 
    corrl = 0
    totClosers = []
    for ll in lines :
        expectedCloser = []
        broke = False
        closers = 0
        for l in ll : 
            if l == '(' :
                expectedCloser.append(')')
            elif l  == '[' :
                expectedCloser.append(']')
            elif l  == '{' :
                expectedCloser.append('}')
            elif l  == '<' :
                expectedCloser.append('>')
            elif l == ')' :
                if l != expectedCloser.pop() :
                    corrl = corrl + 3
                    broke = True
                    break
            elif l  == ']' :
                if l != expectedCloser.pop() :
                    corrl = corrl + 57
                    broke = True
                    break
            elif l  == '}' :
                if l != expectedCloser.pop() :
                    corrl = corrl + 1197
                    broke = True
                    break
            elif l  == '>' :
                if l != expectedCloser.pop() :
                    corrl = corrl + 25137
                    broke = True
                    break
        if not broke:
            for e in expectedCloser[::-1] :
                if e == ")" :
                    closers = (closers*5) + 1
                elif e == "]" :
                    closers = (closers*5) + 2
                elif e == "}" :
                    closers = (closers*5) + 3
                elif e == ">" :
                    closers = (closers*5) + 4
        
            totClosers.append(closers)

    print('10A', corrl)
    totClosers.sort()
    mid = (len(totClosers) ) / 2
   
    print('10B', totClosers[int(mid)] )





task10()

TasK10
10A 436497
10B 2377613374


In [171]:
def task11() : 
    lines = getEachRowAsSingleString("11.txt") 
    dim = 10 
    map = np.zeros((dim,dim))
    
    x = 0
    for ll in lines :
        y = 0 
        for l in ll : 
            map[x,y] = int(l)
            y = y +1     
        x = x + 1
        
    flash = 0 

    for n in range(2000) :
        increaseUs = []
        for x in range(dim) :
            for y in range(dim) : 
                map[x,y] = map[x,y] + 1
                if map[x,y] > 9 :
                    increaseUs.extend(get8Coordineighbours(x,y))                       
                    map[x,y] = 0
                    flash = flash + 1 

        while len(increaseUs) != 0 :
            x,y = increaseUs.pop()
            if x>= 0 and x < dim and y>= 0 and y < dim:
                if map[x,y] != 0 :
                    map[x,y] = map[x,y] + 1 
                    if map[x,y] > 9 :
                        increaseUs.extend(get8Coordineighbours(x,y))                       
                        map[x,y] = 0
                        flash = flash + 1 

        #check if all flash 

        if np.count_nonzero(map) == 0 :
            print("11B", n+1, "All Flash")
            print(map)
            break
        
        if n == 100 :
            print("11A", flash)
            print(map)


task11()

11A 1694
[[1. 1. 7. 7. 3. 0. 6. 0. 0. 0.]
 [1. 5. 3. 2. 3. 5. 0. 0. 0. 0.]
 [3. 3. 2. 2. 2. 5. 0. 0. 8. 0.]
 [2. 2. 2. 2. 2. 5. 0. 0. 7. 0.]
 [2. 2. 2. 2. 2. 4. 0. 0. 6. 0.]
 [2. 2. 2. 2. 2. 7. 7. 3. 5. 0.]
 [2. 2. 2. 2. 6. 4. 4. 7. 4. 0.]
 [2. 2. 2. 7. 4. 3. 4. 7. 5. 0.]
 [9. 2. 2. 7. 6. 6. 7. 4. 0. 0.]
 [7. 9. 6. 2. 2. 2. 4. 0. 0. 0.]]
11B 351 All Flash
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [172]:
def task12() : 
    lines = getEachRowAsSplitList("12.txt", "-")
    graph = {}

    for ll in lines : 
        if ll[0] in graph : 
            graph[ll[0]].append(ll[1])
        else : 
            graph[ll[0]] = [ll[1]]

        if ll[1] in graph : 
            graph[ll[1]].append(ll[0])
        else : 
            graph[ll[1]] = [ll[0]]

    a = depthFirst12A(graph, "start", [], [])
    print("12A", len(a))
   
    paths = []

    for a in graph : 
        if a.islower() :
            if a != "start" and a != "end" :
                res =  depthFirst12B(graph, "start", [], [], a, 2)
                for r in res : 
                    if r not in paths :
                        paths.append(r)
    print("12B", len(paths))

def depthFirst12A(graph, currentVertex, visited, res):
    visitedList = [[]]

    visited.append(currentVertex)
    for vertex in graph[currentVertex]:
        if vertex not in visited or vertex.isupper() :
            depthFirst(graph, vertex, visited.copy(),res)
    visitedList.append(visited)
    if visitedList[1][len(visitedList[1])-1] == "end" :
        res.append(visitedList[1])
    return res


def depthFirst12B(graph, currentVertex, visited, res, allowed, visits):
    visitedList = [[]]

    visited.append(currentVertex)
    for vertex in graph[currentVertex]:
        if vertex not in visited or vertex.isupper() or vertex == allowed:
            if vertex == allowed : 
                if visits != 0 :
                    depthFirst12B(graph, vertex, visited.copy(), res, allowed, visits-1)
            else : 
                depthFirst12B(graph, vertex, visited.copy(), res, allowed, visits)
    visitedList.append(visited)
    if visitedList[1][len(visitedList[1])-1] == "end" :
        res.append(visitedList[1])
    return res

task12()

12A 3495
12B 94849
